
# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Release

on:
  push:
    tags:
    - '*'


jobs:

  xcframework:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-release-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-release
    - name: disable plugin
      run: sed -i.bu 's/^[^#]*.plugin(/\/\/&/' Package.swift
    - name: Create XCFramework
      uses: unsignedapps/swift-create-xcframework@v2
      