# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm   
    - name: disable plugin
      run: sed -i.bu 's/^[^#]*.plugin(/\/\/&/' Package.swift 
    - name: Run build
      run: swift build --disable-sandbox
    - name: Run tests
      run: swift test --disable-sandbox

  xcframework:
    runs-on: macos-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-release-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-release
    - name: disable plugin
      run: sed -i.bu 's/^[^#]*.plugin(/\/\/&/' Package.swift
    - name: run xcframework
      run: |
        brew install mint
        mint install unsignedapps/swift-create-xcframework
        swift create-xcframework --zip